global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'churn-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:${APP_PORT}']

  - job_name: 'cloudflare-tunnel'
    static_configs:
      - targets: [ 'tunnel:2000' ]