name: Deploy Automatico

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/churn-api

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      # Setup do QEMU/Buildx para builds otimizados
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 1. Build e Export para Scan Local (Não sobe ainda)
      - name: Build e Exportar Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # Carrega para o docker daemon local para scanear
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 2. Scan de Imagem (Container Security) - Garante que o OS base é seguro
      - name: Scan de Vulnerabilidades na Imagem (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_IMAGE }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1' # Quebra o deploy se achar algo critico
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # 3. Push da Imagem (Se passou no scan)
      - name: Push da Imagem Final
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            ${{ env.DOCKER_IMAGE }}:latest

      # 4. Deploy no Servidor via SSH
      - name: Atualizar Servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navega para a pasta do projeto (Ajuste o caminho)
            cd /opt/churn-project/infra-ops
            
            # Baixa a nova imagem
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            
            # Recria apenas o container da API (mantendo banco e monitoramento vivos)
            # O docker-compose vai usar a imagem nova por causa da tag :latest
            docker compose up -d --no-deps app
            
            # Limpeza de imagens antigas (dangling)
            docker image prune -f